version: '3.8'

services:
  prodapi-server:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - prodapi-mongo
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DB_NAME}
    networks:
      - prodapi

  prodapi-mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    networks:
      - prodapi

volumes:
  mongo_data:

networks:
  prodapi:
    driver: bridge
